remote_theme: "mmistakes/minimal-mistakes@4.13.0"

title: "NYU Tandon IDM | Special Topics | Micro Environment Exploration Lab 2019"





defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      sidebar:
        nav: "docs"


include: ["_pages"]